export const FORM_LIST_FETCHING = "FORM_LIST_FETCHING";
export const FORM_LIST_FETCHED = "FORM_LIST_FETCHED";
export const FORM_LIST_ERROR = "FORM_LIST_ERROR";

export const CREATE_REFERRAL_POST_POSTING = "CREATE_REFERRAL_POST_POSTING";
export const CREATE_REFERRAL_POST_POSTED = "CREATE_REFERRAL_POST_POSTED";
export const CREATE_REFERRAL_POST_ERROR = "CREATE_REFERRAL_POST_ERROR";
