export const FORM_LIST_FETCHING = "FORM_LIST_FETCHING";
export const FORM_LIST_FETCHED = "FORM_LIST_FETCHED";
export const FORM_LIST_ERROR = "FORM_LIST_ERROR";
export const FORM_LIST_CLEAR = "FORM_LIST_CLEAR";

export const CREATE_REFERRAL_POST_POSTING = "CREATE_REFERRAL_POST_POSTING";
export const CREATE_REFERRAL_POST_POSTED = "CREATE_REFERRAL_POST_POSTED";
export const CREATE_REFERRAL_POST_ERROR = "CREATE_REFERRAL_POST_ERROR";

export const DELETE_REFERRAL_LIST_ITEM_POSTING =
  "DELETE_REFERRAL_LIST_ITEM_POSTING";
export const DELETE_REFERRAL_LIST_ITEM_POSTED =
  "DELETE_REFERRAL_LIST_ITEM_POSTED";
export const DELETE_REFERRAL_LIST_ITEM_ERROR =
  "DELETE_REFERRAL_LIST_ITEM_ERROR";

export const FORM_TEMPLATE_LIST_FETCHING = "FORM_TEMPLATE_LIST_FETCHING";
export const FORM_TEMPLATE_LIST_FETCHED = "FORM_TEMPLATE_LIST_FETCHED";
export const FORM_TEMPLATE_LIST_ERROR = "FORM_TEMPLATE_LIST_ERROR";
export const GET_REFERRAL_FORM_JSON_FETCHING =
  "GET_REFERRAL_FORM_JSON_FETCHING";
export const GET_REFERRAL_FORM_JSON_FETCHED = "GET_REFERRAL_FORM_JSON_FETCHED";
export const GET_REFERRAL_FORM_JSON_ERROR = "GET_REFERRAL_FORM_JSON_ERROR";
